### ISSUE TITLE
Assign task command doesn't work with some commands.

### ISSUE THREAD

**Issue by Yaladah** [AY2223S2-CS2103T-W15-3/tp#82]
`assign` is causing a new task to be created, but when `mark` is called to mark the task as done, status isn't being updated. I suspect the overridden task is the one getting updated but not being reflected.

**Comment by Yaladah** [comment]
It also isn't able to assign people to `todo` and `event` tasks.

**Comment by PawanPatil19** [comment]
It was coded before only for deadline task. It should work now with the addition of new model and task handling.

**Comment by Yaladah** [comment]
Cool
